services:
    divblox:
        build:
            context: .
        env_file:
            - .env
        ports:
            - 3000:3000
    sql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "dxuser"
            MYSQL_PASSWORD: "secret"
            MYSQL_DATABASE: "dx-sveltekit-starter"
        volumes:
            - mysql8data:/var/lib/mysql
        command:
            - --default-authentication-plugin=caching_sha2_password
            - --lower_case_table_names=0
            - --sql_mode=
        ports:
            - 3306:3306
volumes:
    mysql8data: {}
